<#
.SYNOPSIS
    Installs the Crosshair Overlay Game Bar Widget
.DESCRIPTION
    This script sideloads the UWP Game Bar Widget so the crosshair can
    appear in exclusive fullscreen games. Requires Developer Mode or
    sideloading to be enabled in Windows Settings.
.NOTES
    Run this script from the CrosshairOverlay.Widget project directory.
    Must be run as Administrator.
    The .pfx certificate must be generated by building in Visual Studio first.
#>

#Requires -RunAsAdministrator

param(
    [string]$AppxPath = ".\AppPackages\CrosshairOverlay.Widget_*_x64.appx",
    [string]$CertPath = ".\CrosshairOverlay.Widget_TemporaryKey.pfx"
)

$ErrorActionPreference = "Stop"

Write-Host "=== Crosshair Overlay — Game Bar Widget Installer ===" -ForegroundColor Cyan
Write-Host ""

$appx = Get-ChildItem $AppxPath -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $appx) {
    $appxMatches = Get-ChildItem ".\AppPackages\*_x64.appx" -ErrorAction SilentlyContinue
    if ($appxMatches) {
        $appx = $appxMatches | Select-Object -First 1
    }
}
if (-not $appx) {
    $appx = Get-ChildItem ".\AppPackages\*_x64.appxbundle" -ErrorAction SilentlyContinue | Select-Object -First 1
}

if ($appx) {
    Write-Host "Found package: $($appx.Name)" -ForegroundColor Green

    $cert = Get-ChildItem $CertPath -ErrorAction SilentlyContinue
    if (-not $cert) {
        $cert = Get-ChildItem ".\*.pfx" -ErrorAction SilentlyContinue | Select-Object -First 1
    }

    if ($cert) {
        Write-Host "Installing certificate: $($cert.Name)" -ForegroundColor Yellow
        Import-Certificate -FilePath $cert.FullName -CertStoreLocation "Cert:\LocalMachine\TrustedPeople"
        Write-Host "Certificate installed." -ForegroundColor Green
    }
    else {
        Write-Host "No certificate found. If package is signed, certificate must be trusted manually." -ForegroundColor Yellow
    }

    Write-Host "Installing widget package..." -ForegroundColor Yellow
    Add-AppxPackage -Path $appx.FullName
    Write-Host "Widget installed successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "To use the crosshair in exclusive fullscreen:" -ForegroundColor Cyan
    Write-Host "  1. Press Win+G to open Xbox Game Bar" -ForegroundColor White
    Write-Host "  2. Click the Widget Menu button on the Game Bar toolbar" -ForegroundColor White
    Write-Host "  3. Find '准心叠加层' (Crosshair Overlay) and click to open" -ForegroundColor White
    Write-Host "  4. Click the pin icon to keep it visible after Game Bar closes" -ForegroundColor White
    Write-Host "  5. Use the desktop CrosshairOverlay app to customize the crosshair" -ForegroundColor White
}
else {
    Write-Host "ERROR: No .appx or .appxbundle package found." -ForegroundColor Red
    Write-Host ""
    Write-Host "Build the project first:" -ForegroundColor Yellow
    Write-Host "  1. Open CrosshairOverlay.Widget.csproj in Visual Studio" -ForegroundColor White
    Write-Host "  2. Select Build > Publish > Create App Packages" -ForegroundColor White
    Write-Host "  3. Choose 'Sideloading' and follow the wizard" -ForegroundColor White
    Write-Host "  4. Run this script again" -ForegroundColor White
}

Write-Host ""
Read-Host "Press Enter to exit"
